tasks/secure-installation.yml
=> Support for setting root password when running as local_action

tasks/main.yml
On ubuntu 14.04, removing this extra whitespace cleared an error that was halting ansible at line 25 of tasks/configure.yml.
=> eliminates extra whitespace in the variable value

tasks/setup-RedHat.yml
MySQL-python has a dependency of mysql-libs.  If MySQL-python is installed before mysql, mysql-libs will be installed. However, when installing mysql56u (for example) and other versions of mysql, a mysql56u-libs is installed which conflicts with mysql-libs.  
By installing mysql(version) first, mysql(version)-libs will satisfy the requirement for MySQL-python and no conflict arises.
This PR just swaps the order of the install so that MySQL-python is installed after the packages.
=> reversed order of mysql-python install

tasks/secure-installation.yml
When installing mysql56u (and assumedly others), updating the root password on domain.com fails (it says the user does not exist!), at a minimum in vagrant. I have not tested using a box with a valid hostname.   I suspect it has something to do with the fact that it is trying to resolve the hostname and the hostname doesn't exist (updating /etc/hosts doesn't solve, nor does the mysql skip_name_resolve option).
However, the bigger issue, from a security perspective, is that a machine hostname could be changed, resulting in root access from another machine.  
Both of the above issues are solved by simply removing any root user that that doesn't come from localhost, which this PR does.  
Note: doing a "drop user"  fails for the same DNS reasons.
=> Disallow root login remotely

templates/my.cnf.j2
For example, Ubuntu 14.04 /etc/init.d/mysql does not use mysqld_safe
and parses the pidfile out of `mysqld --print-defaults` instead.
---
Without this change:
```
Server version: 5.5.46-0ubuntu0.14.04.2 (Ubuntu)
mysql> show variables like '%pid%';
+---------------+---------------------------------+
| Variable_name | Value                           |
+---------------+---------------------------------+
| pid_file      | /var/lib/mysql/ansible-test.pid |
+---------------+---------------------------------+
```
```
$ /usr/sbin/mysqld --print-defaults | tr ' ' '\n' | grep pid
<no output>
```
With this change:
```
Server version: 5.5.46-0ubuntu0.14.04.2 (Ubuntu)
mysql> show variables like '%pid%';
+---------------+----------------------------+
| Variable_name | Value                      | …
```
=> Set pidfile even when not running via mysqld_safe

.travis.yml, tasks/setup-Debian.yml, tests/Dockerfile.centos-6, tests/Dockerfile.centos-7, tests/Dockerfile.ubuntu-12.04, tests/Dockerfile.ubuntu-14.04, tests/centos-7-test.yml, tests/initctl_faker, tests/test.yml
Over at Drupal VM this role is the one that seems to be failing the most in the Docker tests, so I'm adding the setup here too. Currently everything will fail but maybe travis can help us work through all the errors on at a time. I'm getting some weird inconsistencies when running it locally...
Once we get stuff working we can just create a separate `test.yml` for CentOS 7 (or fix #55, which I'd prefer for upstream tests).
=> Issue #77: Add docker based tests

tasks/users.yml
Without no_log, password would appear in node's syslog.
It's probably unwanted when it comes to password
=> add no_log to operation on confidential data

tasks/configure.yml
We shouldn't be changing the date each time this is run.  While this doesn't make a difference on an installation run, it does make a difference if you are tracking changes.
=> ansible doesn't have a create-if-not-exists

.travis.yml, tasks/configure.yml
This is causing failures on my CentOS7 tests for devshop:
https://travis-ci.org/opendevshop/devshop/jobs/126429109#L1705
The error log file is created but permissions are skipped because they are conditional on `mysql_slow_query_log_enabled`, which I assume was a mistake?
Thanks!
=> Fix "when" statement for mysql error log file permissions.

tasks/main.yml
I would suggest to use {{ ansible_distribution_major_version }} instead of the {{ ansible_lsb.major_release }} since that will require the package redhat-lsb-core installed which is not always installed. You will get the same result if you use the other way without the requirement of redhat-lsb-core package.
=> remove requirement of redhat-lsb-core

tasks/secure-installation.yml
If the role is run in check mode, the shell commands never get executed
and the variables used in the next task are undefined, causing the play
to fail.
The commands are now always executed to ensure the variables are
populated.
=> Fix role failing in check mode

tasks/main.yml, vars/RedHat-7.yml
The file `/vars/RedHat-7.yml` overrides the `mysql_log_error` variable to: "`/var/log/mariadb/mariadb.log`". _This variable can not be overwritten by users of the role._
On my CentOS 7 systems I use the mariaDB packages rather than the CentOS ones so the `/var/log/mariadb` directory does not exist so the `configure.yml` playbook fails when trying to touch that file:
`fatal: [server1]: FAILED! => {"changed": true, "cmd": "touch /var/log/mariadb/mariadb.log", "delta": "0:00:00.004271", "end": "2016-06-14 08:47:03.630648", "failed": true, "rc": 1, "start": "2016-06-14 08:47:03.626377", "stderr": "touch: cannot touch '/var/log/mariadb/mariadb.log': No such file or directory", "stdout": "", "stdout_lines": [], "warnings": ["Consider using file module with state=touch rather than running …
=> Allow RedHat-7 variables to be overridden.

README.md, defaults/main.yml, templates/my.cnf.j2
Some application (owncloud in my case) require to use a different binlog_format than the mysql default (statement), so it could be nice to have the opportunity change it directly from your role! 
So I simply added the variable mysql_binlog_format (with a default value of STATEMENT, which is the default for mysql and mariadb)
This change has been tested on CentOS7 and Ubuntu!
Best regards,
Erkax
=> add mysql_binlog_format directive

defaults/main.yml, templates/my.cnf.j2
This SitePoint tutorial explains our exact reasoning for needing to override this setting: https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/
=> Allow sql_mode to be overridden

defaults/main.yml, templates/my.cnf.j2
I added the `event_scheduler` option, because we had need of it in a project. Here are the docs for that option: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_event_scheduler. I thought it could potentially be useful to others.
=> Add the event_scheduler option to my.cnf.j2 with the default value of 'OFF'

meta/main.yml, tasks/main.yml, tasks/setup-Archlinux.yml, tasks/variables.yml, vars/Archlinux.yml
Hello,
These modifications make your role compatible with Archlinux. It also extends the compatibility as the role does not break if a system does not have its variable file declared. The installation will not be done, but at least the configuration will work
=> Add compatibility with ArchLinux

README.md
This took me about an hour of re-provisioning to figure out that it was doing the install correctly, I was just trying to run mysql from the cli as the wrong user
Signed-off-by: Jeroen v.d. Gulik jeroen@isset.nl
=> Added a gotcha note to the README when trying to login from the CLI

tasks/replication.yml
This adds the REPLICATION CLIENT grant to the replication user,
which is necessary to run the SHOW MASTER STATUS command as a
non-root user.
=> Allow replication against masters without a .my.conf file.

defaults/main.yml, vars/Debian.yml
log_error is required writable directory in MySQL 5.7
https://dev.mysql.com/doc/refman/5.7/en/error-log.html
> It is common for Yum or APT package installations to configure an error log location under /var/log with an entry like log-error=/var/log/mysqld.log in a server configuration file. Removing the file name from the entry causes the default log file to be used, which is written to the data directory.
=> Update default log-error for mysql 5.7

tasks/users.yml
Hi Jeff,
I've added support for providing the encrypted password hash to your mysql_users list.
Kind regards,
Tom van Leeuwen
=> added support for encrypted user passwords

tasks/configure.yml, tasks/secure-installation.yml, templates/my.cnf.j2
This role works great, but some configuration doesn't work for MySQL 8. There's a few variables that aren't supported anymore. See https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html#optvars-removed. I've wrapped those settings around a conditional based on the `mysql_cli_version` fact.
Also I've edited the two tasks that set the root password based on the version so that 8.0 uses the right one.
=> Make the role compatible with MySQL 8

tasks/configure.yml
This fixes #274 caused by my previous PR #273. Since the `my.cnf.j2` template now uses the `msql_cli_version` var to determine if some settings shouldn't be there, it has to always run in normal mode.
Unfortunately when running this role in check mode on a clean host, this task will fail because the `mysql` binary won't initally be available. However, even before PR #273, this role failed in check mode on a clean host on `Set ownership on error log file` because the file wouldn't exist, so I hope the earlier failure now isn't unexpected.
=> Fix #274: Always register the mysql_cli_version variable

tasks/setup-Debian.yml
Fixes the following deprecation warning on Debian-based hosts:
```ansible
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: {{ item }}`, please use `name: u'{{ mysql_packages 
}}'` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
=> Avoid using a loop with the Apt module, because it is deprecated

vars/Debian-10.yml
This aligns the configuration location with the generic Debian variables
file and uses /run instead of /var/run as the latter is the symlink to
the former.
=> Adjust Debian 10 specific settings to the proper values used by the Debian package

tasks/secure-installation.yml
Hi!
Thanks a lot for your so useful Ansible role!
I unfortunately had some problems to run the role without getting an error after the root password has been set or changed.
I left a comment about it on the issue : https://github.com/geerlingguy/ansible-role-mysql/issues/412#issuecomment-717366818
This would be a quick fix but probably not the cleanest.
A better option would be to build the SQL query first in a task using the `with_items` and then run the mysql query in another task so that we can add the flush of privileges at this moment only. But I don't think it's very time consuming to flush the privileges more than once for the case where we have multiple hosts (probably not so often).
Best regards,
Patrick
=> Fixes #412: Flush privileges after root account password update

.github/workflows/ci.yml, tasks/setup-Debian.yml, vars/Debian-11.yml
Debian 11/bullseye vars and adding to ci
Fixes #469
=> Debian 11 support

defaults/main.yml, templates/my.cnf.j2
According to the [mysql dokumentation](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#option_mysqld_log-bin) log-bin is enabled by default and can be disabled using the `disable-log-bin` option. 
Currently it is not possible to disable the log with this ansible role. On unreplicated installations the log is not needed and may induce a significant storage overhead. 
This PR adds an option to disable the log explicitly with a `mysql_disable_log_bin` variable. The log has to be disabled explicitly.
=> Add option to disable binlog

.github/workflows/ci.yml, README.md, tasks/setup-Debian.yml
It seems that #457 may have broken idempotence on Debian 10. Testing to see if that's the case. Don't want to tag broken code in a new release...
=> Fix idempotence for Debian 11 and Debian 10 tests

.github/workflows/ci.yml, meta/main.yml, vars/RedHat-9.yml
Copying the vars from RHEL8 was sufficient to make it work on the current CentOS9 Stream release.
=> Support RHEL9 family

tasks/secure-installation.yml
When MySQL is configured to use [sql_mode ANSI_QUOTES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes), the query in tasks/secure-installation.yml fails:
```
TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] **************************************************************************************************************************************
fatal: [0.0.0.0]: FAILED! => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.015942", "end": "2022-08-10 18:27:01.544215", "msg": "non-zero return code", "rc": 1, "start": "2022-08-10 18:27:01.528273", "stderr": "ERROR 1054 (42S22) at line 1: Unknown column '' in 'where clause'", "stderr_lines": ["ERROR 1054 (42S22) at line 1: Unknown column '' …
```
=> Fix error in query with sql_mode ANSI_QUOTES

README.md, defaults/main.yml, tasks/replication.yml
E.g.
I am running ansible on my local machine and they are accessible over public IP but i want the master and the slave to communicate over some other network interface card.
`mysql_replication_master_inventory_host` defaults to `mysql_replication_master` so it's a non-breaking change
=> Allow replica master to be differ from local inventory + fix Is_Replica or Is_Slave

tasks/configure.yml
More at https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_7.html#removed-features
=> Remove `warn` as it disappeared in Ansible 7

tasks/replication.yml
Fofllow-up to #503. That PR didn't include `Is_Replica` in its `Start replication.` task.
In addition I found that the previous logic of running `Start replication.` when `not slave.Is_Slave` would never start the replica, since `slave.Is_Slave` would evaluate to `true`. The reason being the replication _is_ setup, it just hasn't been started yet, so this PR also fixes that.
=> Fix replication not starting.

tasks/secure-installation.yml
Bug corrected when updating mysql root password for localhost root account (5.7.x).
```
failed: [hostname] (item=localhost) => {"ansible_loop_var": "item", "changed": true, "cmd": "mysql -u root -NBe 'ALTER USER \"root\"@\"localhost\" IDENTIFIED WITH mysql_native_password BY \"xxxxx\"; FLUSH PRIVILEGES;'\n", "delta": "0:00:00.013884", "end": "2023-01-09 11:15:43.965674", "item": "localhost", "msg": "non-zero return code", "rc": 1, "start": "2023-01-09 11:15:43.951790", "stderr": "ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\"xxxxx\"' at line 1", "stderr_lines": ["ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to …
```
=> Bug corrected when updating mysql root password

tasks/setup-Debian.yml
Disable Starting of MySQL Server on Debian based systems during install.
=> Disable Starting of MySQL on Debian during install.

README.md, defaults/main.yml, tasks/replication.yml, tasks/secure-installation.yml, tasks/users.yml
Hi,
This small pull request allows user to hide current plain-text passwords into execution output with the new variable `mysql_hide_passwords`.
The default value of this variable is `false` to allow users to activate this feature if they need it with a minimal impact on their current usage.
Thank you.
=> Hide passwords during execution

vars/Ubuntu.yml
This allows it to be managed by the default logrotate configuration
Fixes #540
=> Set the default Error Log location for Ubuntu

README.md, tasks/users.yml
This fixes the warning message: "Option column_case_sensitive is not provided. The default is now false, so the column's name will be uppercased. The default will be changed to true in community.mysql 4.0.0.".
Resolves #535
=> Introducing the column_case_sensitive for the users task.

defaults/main.yml, templates/my.cnf.j2
Following on this comment in the code : https://github.com/geerlingguy/ansible-role-mysql/commit/e21a22afd48ce2f5e1707ed1875b33ecd162b396#commitcomment-154694645
This reintroduces `query_cache_*` variables for MariaDB users. This disappeared in #561 as I thought at the time it was OK to just remove these variables from MariaDB configuration. I was wrong :D
Thanks,
Regards
=> fix: query caching features on mariadb
