geerlingguy/ansible-role-mysql

tasks/main.yml, tasks/secure-installation.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml
=> Set fact to check package installation regardless of distribution

tasks/users.yml
I need one user to access two different databases, with this change I can handle it.
=> Allow append privileges

README.md, defaults/main.yml, tasks/configure.yml, templates/my.cnf.j2, vars/Debian.yml, vars/RedHat.yml
This is the same as PR #31 but that repo was moved.
=> Allow configuration of variables not currently supported

defaults/main.yml, tasks/configure.yml, templates/my.cnf.j2
=> Fixes #63: Running role on Ubuntu 15/16.04 fails.

defaults/main.yml, templates/my.cnf.j2
This prevent MySQL DNS name resolution.
Default: false
=> Add mysql_skip_name_resolve parameter

templates/user-my.cnf.j2
Adds quotes around password value.
=> Fix for complex passwords in .my.cnf

tasks/secure-installation.yml
See: https://github.com/geerlingguy/drupal-vm/issues/650 and http://dev.mysql.com/doc/refman/5.7/en/default-privileges.html
=> Update secure-installation for correct root password in 5.7+.

tasks/setup-Debian.yml
Using ansible file module instead of rm command
=> using file module instead of rm

tasks/main.yml, vars/RedHat-7.yml
Reverts geerlingguy/ansible-role-mysql#132
=> Revert "Allow RedHat-7 variables to be overridden."

.travis.yml
See for more info: https://github.com/travis-ci/travis-ci/issues/6461#issuecomment-239577306
=> Fix Travis CI test failures

.travis.yml, tests/Dockerfile.ubuntu-16.04
=> Fixes #109: Add Docker test on Travis for Ubuntu 16.04.

tasks/replication.yml
=> Fix mysql_replication conditionals for Ansible 2.2

README.md, defaults/main.yml, tasks/secure-installation.yml, templates/root-my.cnf.j2, templates/user-my.cnf.j2
Following up to https://github.com/geerlingguy/ansible-role-mysql/pull/104
=> More correctly and automatically support running the role as a user other than root

templates/my.cnf.j2, templates/root-my.cnf.j2, templates/user-my.cnf.j2
Modified   templates/my.cnf.j2
Modified   templates/root-my.cnf.j2
Modified   templates/user-my.cnf.j2
=> fixes #225 include ansible_managed in templates.

tasks/databases.yml
Right now the state for databases is hard-coded to present. It would be useful to allow databases to be deleted from within the role.
=> Allow databases to be deleted

tasks/setup-Debian.yml
Rebase of https://github.com/geerlingguy/ansible-role-mysql/pull/248
=> Infer required Python library from interpreter

meta/main.yml, tasks/setup-RedHat.yml, vars/RedHat-8.yml
Opened up an issue as well #367
=> Add support for CentOS 8/RedHat 8

tasks/replication.yml
=> Fixes #401: Make sure mysql_replication_master is evaluated as boolean properly.

.github/workflows/ci.yml
=> Issue #422: Attempt to disable AppArmor to get MySQL to run in container.

handlers/main.yml, tasks/configure.yml, tasks/replication.yml, tasks/secure-installation.yml, tasks/setup-Debian.yml
Related: https://ansible-lint.readthedocs.io/rules/no-free-form/
=> Fix no-free-form rule violation

handlers/main.yml, molecule/default/converge.yml, tasks/configure.yml, tasks/main.yml, tasks/secure-installation.yml, tasks/setup-Archlinux.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml, tasks/variables.yml
Related: https://ansible-lint.readthedocs.io/rules/fqcn/
=> Use fqcn actions

tasks/replication.yml, tasks/setup-Archlinux.yml, tasks/setup-Debian.yml
Related: https://ansible-lint.readthedocs.io/rules/no-free-form/
=> Address no-free-form ansible-lint rule
